### ISSUE TITLE
Decouple "admin" and "mod" roles

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/dao#3]
Currently, snapshot admins are able to both edit the space settings and moderate proposals.

As part of [GIP-77](https://forum.gnosis.io/t/gip-77-should-the-gnosisdao-add-delegation-spam-reduction/6362?u=auryn_macmillan), we would like to add a new "moderator" role to decouple the moderator permissions from the admin role.

The desired role structure looks as follows:
- **Admin:** able to edit the space settings.
- **Moderator:** able to moderate proposals.
- **Author:** able to create proposals without constraints.
- **Everyone:** able to vote in proposals and able create proposals if they pass validation.

This issue should be implemented via a PR to the [snapshot codebase](https://github.com/snapshot-labs/snapshot), including [updates to their documentation](https://docs.snapshot.org/spaces/settings#admins-and-authors).

**Comment by zzuziak** [comment]
Hey @auryn-macmillan, let us know your thoughts on the solution from the above PR. You can have a look at it live here: https://snapshot.org/#/gnosis.eth/settings

**Comment by auryn-macmillan** [comment]
Looks awesome! I had a play with it earlier and it seems to do what we need.
Appreciate the support on this.
